version: '3.8'
services:
  wg-easy:
    image: wg-easy
    command: npm run serve
    volumes:
      - ./src/:/app/
    environment: 
      # - PASSWORD=p
      - WG_HOST=192.168.1.233
      # - METRICS_ENABLED=true
      # - METRICS_USER=u
      # - METRICS_PASSWORD=p
